# SPDX-FileCopyrightText: mpvQC developers
#
# SPDX-License-Identifier: MIT

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        #  - repo: https://github.com/biomejs/pre-commit
        #    rev: v2.2.5
        #    hooks:
        #      - id: biome-check
        #        name: "format json"
        #        files: "\\.(jsonc?)$"
        #        args: &BIOME_ARGS
        #          - "--bracket-spacing=true"
        #          - "--indent-style=space"
        #          - "--indent-width=4"
        #          - "--line-ending=lf"
        #          - "--line-width=120"
        #      - id: biome-check
        #        name: "format js"
        #        files: "\\.js$"
        #        args: *BIOME_ARGS
  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
        name: "format toml"
        args:
          - "--option"
          - "align_comments=true"
          - "--option"
          - "allowed_blank_lines=1"
          - "--option"
          - "array_auto_collapse=false"
          - "--option"
          - "indent_string=    "
  - repo: https://github.com/google/yamlfmt
    rev: v0.20.0
    hooks:
      - id: yamlfmt
        name: "format yml"
        args:
          - "-formatter"
          - "line_ending=lf"
          - "-formatter"
          - "retain_line_breaks_single=true"
          - "-formatter"
          - "scan_folded_as_literal=true"
  - repo: https://github.com/hukkin/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
        name: "format md"
        exclude: ".github/"
        args:
          - "--number"
          - "--wrap"
          - "keep"
          - "--end-of-line"
          - "lf"
        additional_dependencies:
          - mdformat-gfm
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.8
    hooks:
      - id: ruff
        name: "lint py"
        args:
          - "--fix"
      - id: ruff-format
        name: "format py"
  - repo: https://github.com/tomas-krupa/qmlformat-hook.git
    rev: 1.2.0
    hooks:
      - id: qmlformat
        files: '.*\.qml$'
        name: "format qml"
        args:
          - --newline=unix
  - repo: https://github.com/fsfe/reuse-tool
    rev: v6.2.0
    hooks:
      - id: reuse-lint-file
        name: "lint licenses"
