# SPDX-FileCopyrightText: mpvQC developers
#
# SPDX-License-Identifier: MIT

version = 1

[[annotations]]
path = ".github/ISSUE_TEMPLATE/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "mpvQC developers"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ".github/[QC]_screenshot-qc.txt"
precedence = "aggregate"
SPDX-FileCopyrightText = "mpvQC developers"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ".github/screenshot.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "mpvQC developers"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "build-aux/windows-icon.ico"
precedence = "aggregate"
SPDX-FileCopyrightText = "mpvQC developers"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "build-aux/windows-splash.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "mpvQC developers"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "data/themes.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "mpvQC developers"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "data/fonts/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "The Noto Project Authors"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = "data/icons/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Google Inc."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "data/config/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "mpvQC developers"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "i18n/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "mpvQC developers"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "NOTICE.txt"
precedence = "aggregate"
SPDX-FileCopyrightText = "mpvQC developers"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "LICENSES/PSF-2.0.txt"
precedence = "aggregate"
SPDX-FileCopyrightText = "mpvQC developers"
SPDX-License-Identifier = "PSF-2.0"

[[annotations]]
path = "uv.lock"
precedence = "aggregate"
SPDX-FileCopyrightText = "mpvQC developers"
SPDX-License-Identifier = "MIT"
